# Generated by Django 4.2.9 on 2025-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_bookmark_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_visitor',
            },
        ),
    ]
